dataset:
  base: src.utils.registry.get_imagenet
  root: ./data
  val_ratio: 0.2
device: cuda
experiment_name: clf_imagenet_resnet50_none_42
model:
  hidden_dim: 128
  input_shape:
  - 3
  - 224
  - 224
  name: resnet50
  num_classes: 1000
regularization:
  metric: none
  weight: 0.0
seed: 42
train:
  batch_size: 64
  epochs: 10
  lr: 0.001
