dataset:
  base: src.utils.registry.get_mnist
  root: ./data
  transform: src.utils.registry.default_mnist_transform
  val_ratio: 0.2
device: cuda
experiment_name: clf_mnist_resnet101_2025
model:
  hidden_dim: 128
  input_shape:
  - 1
  - 28
  - 28
  name: resnet101
  num_classes: 10
regularization:
  metric: info_nce
  weight: 0.0
seed: 2025
train:
  batch_size: 64
  epochs: 10
  lr: 0.001
