dataset:
  base: src.utils.registry.get_mnist
  root: ./data
  transform: src.utils.registry.default_mnist_transform
  val_ratio: 0.2
device: cuda
experiment_name: clf_mnist_simple_cnn_combined_42
model:
  hidden_dim: 128
  input_shape:
  - 1
  - 28
  - 28
  name: simple_cnn
  num_classes: 10
regularization:
  geodesic_ratio:
    lambda_reg: 0.1
    n_neighbors: 10
    target_ratio: 1.0
  geometry_mark:
    lambda_reg: 0.1
    margin: 0.1
  metric: combined
  weight: 0.1
seed: 42
train:
  batch_size: 64
  epochs: 10
  lr: 0.001
