dataset:
  base: src.utils.registry.get_imagenet
  root: ./data
  val_ratio: 0.2
device: cuda
experiment_name: clf_imagenet_resnet101_geometry_2025
model:
  hidden_dim: 128
  input_shape:
  - 3
  - 224
  - 224
  name: resnet101
  num_classes: 1000
regularization:
  geometry_mark:
    lambda_reg: 0.1
    margin: 0.1
  metric: geometry
  weight: 0.1
seed: 2025
train:
  batch_size: 64
  epochs: 10
  lr: 0.001
