dataset:
  base: src.utils.registry.get_cifar10
  root: ./data
  transform: src.utils.registry.default_mnist_transform
  val_ratio: 0.2
device: cuda
experiment_name: clf_cifar10_simple_cnn_geodesic_2025
model:
  hidden_dim: 128
  input_shape:
  - 3
  - 32
  - 32
  name: simple_cnn
  num_classes: 10
regularization:
  geodesic_ratio:
    lambda_reg: 0.1
    n_neighbors: 10
    target_ratio: 1.0
  metric: geodesic
  weight: 0.1
seed: 2025
train:
  batch_size: 64
  epochs: 10
  lr: 0.001
